# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44e879f1f0fbe4c63737714645c7cb9fa4dfe91f4db0b28a93ff3ec38d97327de34adea87c0fb1ee4f38339e1c8d3b735bad494296301cb4bdf0dfb5f7bf766e

test:
  secret_key_base: fbe3d33d8505d230a8e3e0a761c79d2bf229973d11cc9e4cf67450d8f7649a5219e4e73cfa78b4aa7b4e5230e83355c329dc3efe9df407bc13bcf13f09740e06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
